import Head from 'next/head'
import Navbar from '../components/Navbar'
import Content from '../components/Content'
import Card from '../components/Card'
export default function Home() {
  return (
    <div >
      <Head>
        <title>Assignment 1 in Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

      <Navbar />
      <Content />
      <Card />
      </main>
    </div>
  )
}
